# Generated by Django 6.0 on 2026-04-15 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0003_lodge_bronirui_online_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории (например: На воде)', max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Уникальный URL-адрес категории в рамках типа размещения', max_length=255, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lodges/categories/', verbose_name='Фотография')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('lodge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='lodges.lodgetype', verbose_name='Тип размещения')),
            ],
            options={
                'verbose_name': 'Категория размещения',
                'verbose_name_plural': 'Категории размещения',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lodge',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lodges', to='lodges.lodgecategory', verbose_name='Категория размещения'),
        ),
        migrations.AddConstraint(
            model_name='lodgecategory',
            constraint=models.UniqueConstraint(fields=('lodge_type', 'slug'), name='unique_lodge_category_slug_per_type'),
        ),
    ]
