# Generated by Django 6.0 on 2026-04-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_nav_show_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afishaevent',
            name='event_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания события'),
        ),
        migrations.AddField(
            model_name='afishaevent',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='afishaevent',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата события'),
        ),
    ]
