# Generated by Django 6.0 on 2026-04-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_afishaevent_event_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afishaevent',
            name='event_date',
            field=models.DateField(null=True, verbose_name='Дата события'),
        ),
        migrations.AlterField(
            model_name='afishaevent',
            name='short_description',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
    ]
