# Generated by Django 6.0 on 2026-04-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_afishaevent_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afishaevent',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата события'),
        ),
    ]
